export const sampleTestData = {
  userData: [
    {"id": 1, "name": "Mike Wazoski"},
    {"id": 2, "name": "James Sullivan"},
    {"id": 3, "name": "Randall Boggs"},
    {"id": 4, "name": "Boo"}
  ],
  roomData: [
    {"number": 10,
    "roomType": "residential suite",
    "bidet": true,
    "bedSize": "queen",
    "numBeds": 3,
    "costPerNight": 350},
    {"number": 11,
    "roomType": "junior suite",
    "bidet": true,
    "bedSize": "full",
    "numBeds": 2,
    "costPerNight": 275},
    {"number": 12,
    "roomType": "single room",
    "bidet": false,
    "bedSize": "queen",
    "numBeds": 1,
    "costPerNight": 200},
    {"number": 13,
    "roomType": "suite",
    "bidet": false,
    "bedSize": "queen",
    "numBeds": 2,
    "costPerNight": 325}
  ],
  bookingData: [
    {"id": "5fwrgu4i7k55hl6t5",
    "userID": 2,
    "date": "2020/11/03",
    "roomNumber": 11},
    {"id": "5d5dfufjslkam31d7",
    "userID": 1,
    "date": "2020/10/31",
    "roomNumber": 12},
    {"id": "9s72kfncs86grssap",
    "userID": 3,
    "date": "2020/11/03",
    "roomNumber": 12},
    {"id": "dh26skcn589za8d52k",
    "userID": 1,
    "date": "2021/10/30",
    "roomNumber": 10}
  ],
  mappedBookingData: [
    {"id": "5fwrgu4i7k55hl6t5",
    "userID": 2,
    "date": new Date("2020/11/03").toLocaleDateString(),
    "roomNumber": 11,
    "cost": 275},
    {"id": "5d5dfufjslkam31d7",
    "userID": 1,
    "date": new Date("2020/10/31").toLocaleDateString(),
    "roomNumber": 12,
    "cost": 200},
    {"id": "9s72kfncs86grssap",
    "userID": 3,
    "date": new Date("2020/11/03").toLocaleDateString(),
    "roomNumber": 12,
    "cost": 200},
    {"id": "dh26skcn589za8d52k",
    "userID": 1,
    "date": new Date("2021/10/30").toLocaleDateString(),
    "roomNumber": 10,
    "cost": 350}
  ]
}
